version: '3.8'

networks:
  flash-sale-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: flash-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    networks:
      - flash-sale-network
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/

  redis:
    image: redis:latest
    container_name: flash-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - flash-sale-network

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: flash-zookeeper
    ports:
      - "2181:2181"
    networks:
      - flash-sale-network

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: flash-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: flash-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # 외부 클라이언트가 접근할 주소
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # 모든 인터페이스에서 수신 가능
    networks:
      - flash-sale-network
    depends_on:
      - zookeeper