version: '3.8'

networks:
  delivery-system-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: flash-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    networks:
      - flash-sale-network
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/

  redis:
    image: redis:latest
    container_name: flash-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - flash-sale-network