global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flash-sale'
    static_configs:
      - targets: [ 'host.docker.internal:19300' ]
    metrics_path: '/actuator/prometheus'
  - job_name: 'gateway'
    static_configs:
      - targets: [ 'host.docker.internal:19091' ]
    metrics_path: '/actuator/prometheus'
  - job_name: 'order'
    static_configs:
      - targets: [ 'host.docker.internal:19400' ]
    metrics_path: '/actuator/prometheus'
  - job_name: 'alarm'
    static_configs:
      - targets: [ 'host.docker.internal:19600' ]
    metrics_path: '/actuator/prometheus'
  - job_name: 'auth'
    static_configs:
      - targets: [ 'host.docker.internal:19100' ]
    metrics_path: '/actuator/prometheus'
  - job_name: 'user'
    static_configs:
      - targets: [ 'host.docker.internal:19200' ]
    metrics_path: '/actuator/prometheus'
  - job_name: 'vendor'
    static_configs:
      - targets: [ 'host.docker.internal:19500' ]
    metrics_path: '/actuator/prometheus'