server:
  port: ${FLASH_SALE_PORT}

spring:
  application:
    name: flash-sale
  datasource:
    url: ${DB_DATABASE}/flashsales
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS}
  jpa:
    hibernate:
      ddl-auto: ${DDL}
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DOMAIN}:${EUREKA_PORT}/eureka/

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: ${FLASH_SALE_API_DOCS_PATH}
    enable-spring-security: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json