server:
  port: ${USER_PORT}

spring:
  application:
    name: user
  datasource:
    url: ${DB_DATABASE}/users
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DOMAIN}:${EUREKA_PORT}/eureka/

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: ${USER_API_DOCS_PATH}
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

management:
  server:
    port: ${USER_PORT}
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true