server:
  port: ${ORDER_PORT}

spring:
  application:
    name: order

  datasource:
    url: ${DB_URL}/orders
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#결제 api
iamport:
  apiKey: ${IAMPORT_API_KEY}
  apiSecret: ${IAMPORT_API_SECRET}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DOMAIN}:${EUREKA_PORT}/eureka/
