server:
  port: ${ALARM_PORT}

spring:
  application:
    name: alarm
  datasource:
    url: ${DB_DATABASE}/alarms
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
  mail:
    host: ${MASTER_HOST}
    port: 587
    username: ${MASTER_USERNAME}
    password: ${MASTER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DOMAIN}:${EUREKA_PORT}/eureka/

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: ${ALARM_API_DOCS_PATH}
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json