name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ dev ]
    types: [ opened , synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: action checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run build
        run: ./gradlew clean build -x test

      - name: Compress projects
        run: zip -r ./backend.zip .

      - name: Transfer project to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend.zip"
          target: "/home/ubuntu/flash-sale/backend/"

      - name: Deploy to EC2 using Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/flash-sale/backend
            unzip backend.zip
            
            # Stop and remove existing containers
            docker-compose -p flash stop -v || true
            
            # Build the new images
            docker-compose build
            
            # Run the new containers
            docker-compose -p flash up -d --build
