server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  data:
    redis:
      host: ${REDIS_DOMAIN}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jpa:
    enabled: false


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DOMAIN}:${EUREKA_PORT}/eureka/

springdoc:
  swagger-ui:
    use-root-path: true
    urls[0]:
      name: 인증 API
      url: ${GATEWAY_DOMAIN}:${GATEWAY_PORT}${AUTH_API_DOCS_PATH}
    urls[1]:
      name: 사용자 API
      url: ${GATEWAY_DOMAIN}:${GATEWAY_PORT}${USER_API_DOCS_PATH}
    urls[2]:
      name: 플래시 세일 API
      url: ${GATEWAY_DOMAIN}:${GATEWAY_PORT}${FLASH_SALE_API_DOCS_PATH}
    urls[3]:
      name: 주문 결제 API
      url: ${GATEWAY_DOMAIN}:${GATEWAY_PORT}${ORDER_API_DOCS_PATH}
    urls[4]:
      name: 업체 상품 API
      url: ${GATEWAY_DOMAIN}:${GATEWAY_PORT}${VENDOR_API_DOCS_PATH}

management:
  server:
    port: ${GATEWAY_PORT}
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true